version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/data/postgres'
      - './sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    env_file:
      - docker.env

    environment:
      POSTGRES_DB: desire
      POSTGRES_PASSWORD: postgres

    logging:
      options:
        max-size: 10m
        max-file: '3'

volumes:
  postgres_data: {}
